{ lib, ... }:

{
  # Open port 5173 for dev server
  networking.firewall.allowedTCPPorts = [ 5173 ];

  # Disable systemd-networkd (use traditional networking for static IPs)
  networking.useNetworkd = lib.mkForce false;
  systemd.network.enable = lib.mkForce false;

  # Static networking configuration for Hetzner Cloud
  # Generated by nixos-infect, preserved here for flake deployment
  networking = {
    nameservers = [
      "2a01:4ff:ff00::add:2"
      "2a01:4ff:ff00::add:1"
      "185.12.64.1"
    ];

    defaultGateway = "172.31.1.1";
    defaultGateway6 = {
      address = "fe80::1";
      interface = "eth0";
    };

    dhcpcd.enable = false;
    usePredictableInterfaceNames = lib.mkForce false;

    interfaces = {
      eth0 = {
        ipv4.addresses = [
          { address = "77.42.27.244"; prefixLength = 32; }
        ];
        ipv6.addresses = [
          { address = "2a01:4f9:c013:57df::1"; prefixLength = 64; }
          { address = "fe80::9000:7ff:fe05:35f9"; prefixLength = 64; }
        ];
        ipv4.routes = [
          { address = "172.31.1.1"; prefixLength = 32; }
        ];
        ipv6.routes = [
          { address = "fe80::1"; prefixLength = 128; }
        ];
      };
    };
  };

  # Ensure consistent interface naming
  services.udev.extraRules = ''
    ATTR{address}=="92:00:07:05:35:f9", NAME="eth0"
  '';
}
